# Generated by Django 5.2.16 on 2026-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_followups_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='draft_text',
            field=models.TextField(blank=True, default='', help_text='LLM-proposed message text awaiting HITL review.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
