# Generated by Django 5.2.16 on 2026-07-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_reminder_draft_text_alter_reminder_status'),
        ('tenants', '0004_tenant_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_followups', to='followups.reminder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successful_followups', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-sent_at'], name='followups_s_tenant__596109_idx')],
            },
        ),
    ]
