# Generated by Django 5.2.16 on 2026-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoices_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringschedule',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
