# Generated by Django 5.2.16 on 2026-07-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('form', 'Form'), ('csv', 'CSV/Excel'), ('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('dispatched', 'Dispatched'), ('dead', 'Dead')], default='pending', max_length=12)),
                ('raw', models.JSONField(default=dict)),
                ('mapped', models.JSONField(default=dict)),
                ('target_type', models.CharField(default='contact', max_length=40)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataentry_records', to='tenants.tenant')),
            ],
        ),
    ]
