# Generated by Django 5.2.16 on 2026-07-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 secret used to verify inbound webhook payloads.', max_length=64),
        ),
    ]
