# Generated by Django 5.2.16 on 2026-07-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskrecord",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_records",
                to="workflows.event",
            ),
        ),
    ]
