# Generated by Django 5.2.16 on 2026-07-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('input_hash', models.CharField(max_length=64)),
                ('output_hash', models.CharField(max_length=64)),
                ('guard_decisions', models.JSONField(default=list)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('langsmith_trace_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'agent_name', 'created_at'], name='ai_audit_ll_tenant__1bdd52_idx')],
            },
        ),
    ]
