# Generated by Django 5.2.16 on 2026-07-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_tenant_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("crm", "CRM"),
                            ("billing", "Billing"),
                            ("storage", "Storage"),
                            ("chat", "Chat"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credentials", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "kind"), name="uniq_tenant_kind"
                    )
                ],
            },
        ),
    ]
