# Generated by Django 5.2.16 on 2026-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='vendor',
            field=models.CharField(blank=True, default='minio', max_length=20),
        ),
    ]
